# Generated by Django 2.2.2 on 2019-06-17 11:16

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0002_auto_20170322_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amaitutakojokoak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amaitutakoak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='gameruser',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo'),
        ),
        migrations.AlterField(
            model_name='gameruser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='jokuplataforma',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plataforma', to=settings.AUTH_USER_MODEL),
        ),
    ]
